export const Home = lazy(() => import('@/views/home'))
export const Hellow1 = lazy(() => import('@/views/hellow'))
export const Hellow2 = lazy(() => import('@/views/hellow2'))
export const CanvasControl = lazy(() => import('@/views/canvas-control'))
export const GoldenModalDemo = lazy(() => import('@/components/GoldenModal/demo'))
