/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const Button: typeof import('antd/es')['Button']
  const Card: typeof import('antd/es')['Card']
  const DesktopOutlined: typeof import('@ant-design/icons')['DesktopOutlined']
  const FileOutlined: typeof import('@ant-design/icons')['FileOutlined']
  const Layout: typeof import('antd/es')['Layout']
  const Menu: typeof import('antd/es')['Menu']
  const PieChartOutlined: typeof import('@ant-design/icons')['PieChartOutlined']
  const TeamOutlined: typeof import('@ant-design/icons')['TeamOutlined']
  const UploadOutlined: typeof import('@ant-design/icons')['UploadOutlined']
  const UserOutlined: typeof import('@ant-design/icons')['UserOutlined']
  const VideoCameraOutlined: typeof import('@ant-design/icons')['VideoCameraOutlined']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
